# kubectl run nginx --image=nginx
# kubectl describe pod newpods-<id>
# kubectl run redis --image=redis123 --dry-run=client -o yaml > redis-definition.yaml

apiVersion: v1
kind: Pod
metadata:
 name: nginx
spec:
 containers:
  - name: webserver
    image: nginx
    ports:
      - containerPort: 80
       